### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by timsayshey** [Maschell/JWUDTool#1]
Tried this out on a wudump however I received the following error. Please advise. Thanks!

```
Tims-MacBook-Pro:wudump timb$ /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java -jar JWUDTool.jar -compress -in game_part1.wud
JWUDTool 0.1 - Maschell

Commonkey was set to: -snip-
Compressing: game_part1.wud
Parsing WUD image.
Dec 22, 2016 1:23:36 PM de.mas.jnus.lib.implementations.wud.WUDImage <init>
INFO: Image is splitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
	at de.mas.jnus.lib.implementations.wud.WUDImage.calculateSplittedFileSize(WUDImage.java:98)
	at de.mas.jnus.lib.implementations.wud.WUDImage.getWUDFileSize(WUDImage.java:85)
	at de.mas.jnus.lib.WUDService.compressWUDToWUX(WUDService.java:41)
	at de.mas.jnus.lib.WUDService.compressWUDToWUX(WUDService.java:32)
	at de.mas.jwudtool.Main.compressWUD(Main.java:262)
	at de.mas.jwudtool.Main.main(Main.java:99)
	... 5 more
```

**Comment by timsayshey** [comment]
Nevermind -- the wud files needed to be combined first. Probably need to add a noob friendly guide ;)

**Comment by Maschell** [comment]
The wud files don't need to be combined first. Maybe you're using openJDK?

**Comment by timsayshey** [comment]
I'm using jdk1.8.0_102.jdk on a mac. Also, what filetype should the output be? .app?

**Comment by Maschell** [comment]
Should be fixed with the 0.1b version, can you confirm it?

**Comment by timsayshey** [comment]
Yeah, can you include the jar file plz?

**Comment by timsayshey** [comment]
Also, what do I set the -out parameter to? game.app?

**Comment by Maschell** [comment]
Look at the Release Tab.
https://github.com/Maschell/JWUDTool/releases/tag/0.1b

What you want to do? When you provide no -out parameter default values will be used

**Comment by timsayshey** [comment]
The latest release does not include the pre compiled jar file

**Comment by Maschell** [comment]
My bad, should be Online now, sorry

**Comment by timsayshey** [comment]
It worked! Thanks! Btw, how do I output a format for loading via the Brazilian method? (aka WUP Installer Mod Y)
