### ISSUE TITLE
hash checksum failed

### ISSUE THREAD

**Issue by korewatori** [Maschell/JWUDTool#10]
```
Exception in thread "main" java.io.IOException: de.mas.wiiu.jnus.utils.CheckSumWrongException: hash checksum failed
        at de.mas.wiiu.jnus.implementations.DefaultNUSDataProcessor.readPlainDecryptedContentToStream(DefaultNUSDataProcessor.java:195)
        at de.mas.wiiu.jnus.interfaces.NUSDataProcessor.readPlainDecryptedContent(NUSDataProcessor.java:85)
        at de.mas.wiiu.jnus.interfaces.NUSDataProcessor.readPlainDecryptedContent(NUSDataProcessor.java:79)
        at de.mas.wiiu.jnus.NUSTitleLoader.loadNusTitle(NUSTitleLoader.java:104)
        at de.mas.wiiu.jnus.WUDLoader.convertGamePartitionToNUSTitle(WUDLoader.java:113)
        at de.mas.wiiu.jnus.WUDLoader.getPartitonsAsFSTDataProvider(WUDLoader.java:123)
        at de.mas.jwudtool.Main.decryptFile(Main.java:268)
        at de.mas.jwudtool.Main.decrypt(Main.java:301)
        at de.mas.jwudtool.Main.main(Main.java:153)
Caused by: de.mas.wiiu.jnus.utils.CheckSumWrongException: hash checksum failed
        at de.mas.wiiu.jnus.implementations.DefaultNUSDataProcessor.processNonHashedStream(DefaultNUSDataProcessor.java:279)
        at de.mas.wiiu.jnus.implementations.DefaultNUSDataProcessor.readPlainDecryptedContentToStream(DefaultNUSDataProcessor.java:193)
        ... 8 more
```

I get this when trying to extract things from a Kiosk .WUX file (October 2016 one, if that helps)
I don't think the file is damaged, The MD5 is 74d99ca08597f46546f838f216e4220e and the SHA-256 is 58026be931fe8fcc17548e93826edda1605d78a9, are these right?

**Comment by Maschell** [comment]
Whats are your cmd line arguments? Did you use `--dev`?
