### ISSUE TITLE
java.lang.IllegalArgumentException: Missing argument

### ISSUE THREAD

**Issue by t0int** [Maschell/JWUDTool#14]
JWUDTool 0.4 - Maschell

Extracting WUD
Extracting: hidden
Exception in thread "main" java.lang.IllegalArgumentException: Missing argument
        at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
        at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.init(AESDecryption.java:57)
        at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.init(AESDecryption.java:52)
        at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.<init>(AESDecryption.java:48)
        at de.mas.wiiu.jnus.entities.Ticket.calculateDecryptedKey(Ticket.java:84)
        at de.mas.wiiu.jnus.entities.Ticket.createTicket(Ticket.java:78)
        at de.mas.wiiu.jnus.entities.Ticket.parseTicket(Ticket.java:71)
        at de.mas.wiiu.jnus.NUSTitleLoader.loadNusTitle(NUSTitleLoader.java:68)
        at de.mas.wiiu.jnus.WUDLoader.convertGamePartitionToNUSTitle(WUDLoader.java:113)
        at de.mas.wiiu.jnus.WUDLoader.getGamePartionsAsNUSTitles(WUDLoader.java:103)
        at de.mas.jwudtool.Main.extract(Main.java:219)
        at de.mas.jwudtool.Main.main(Main.java:169)

**Comment by Komak57** [comment]
use the -commonkey argument to get around this message
