### ISSUE TITLE
exeption in thread main

### ISSUE THREAD

**Issue by AmikadM** [Maschell/JWUDTool#17]
i got this

Exception in thread "main" java.io.IOException: WiiUDiscContentsHeader MAGIC mismatch.
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUDiscContentsHeader.parseData(WiiUDiscContentsHeader.java:39)
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUContentsInformation.parseData(WiiUContentsInformation.java:22)
        at de.mas.wiiu.jnus.implementations.wud.header.WiiUDiscHeader.parseData(WiiUDiscHeader.java:25)
        at de.mas.wiiu.jnus.implementations.wud.WiiUDisc.parseData(WiiUDisc.java:20)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:91)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:69)
        at de.mas.jwudtool.Main.extract(Main.java:209)
        at de.mas.jwudtool.Main.main(Main.java:169)

plz help

**Comment by Jonah-multi** [comment]
I believe that it's a similar issue to #11, but I'm bringing it up again because I've got the same issue but with Skylanders Giants, which never had a Digital Release and doesn't have a title.key. If someone else knows how to fix this, that'd be excellent.
