### ISSUE TITLE
Unable to extract .app from a WUD or WUX files

### ISSUE THREAD

**Issue by TLiley2** [Maschell/JWUDTool#21]
I am unable to extract the needed .app from either the games WUD or WUX files due to this error

`Microsoft Windows [Version 10.0.19045.4291]
(c) Microsoft Corporation. All rights reserved.

C:\Users\###\Downloads\sonic-boom-rise-of-lyric-development-build>java -jar JWUDTool-0.4.jar -in "game.wud" -out "extracted" -extract all
JWUDTool 0.4 - Maschell

Extracting WUD
Extracting: C:\Users\###\Downloads\sonic-boom-rise-of-lyric-development-build\game.wud
Exception in thread "main" java.io.IOException: WiiUDiscContentsHeader MAGIC mismatch.
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUDiscContentsHeader.parseData(WiiUDiscContentsHeader.java:39)
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUContentsInformation.parseData(WiiUContentsInformation.java:22)
        at de.mas.wiiu.jnus.implementations.wud.header.WiiUDiscHeader.parseData(WiiUDiscHeader.java:25)
        at de.mas.wiiu.jnus.implementations.wud.WiiUDisc.parseData(WiiUDisc.java:20)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:91)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:69)
        at de.mas.jwudtool.Main.extract(Main.java:209)
        at de.mas.jwudtool.Main.main(Main.java:169)

C:\Users\###\Downloads\sonic-boom-rise-of-lyric-development-build>java -jar JWUDTool-0.4.jar -in "game.wux" -out "extracted" -extract all
JWUDTool 0.4 - Maschell

Extracting WUD
Extracting: C:\Users\###\Downloads\sonic-boom-rise-of-lyric-development-build\game.wux
Exception in thread "main" java.io.IOException: WiiUDiscContentsHeader MAGIC mismatch.
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUDiscContentsHeader.parseData(WiiUDiscContentsHeader.java:39)
        at de.mas.wiiu.jnus.implementations.wud.content.WiiUContentsInformation.parseData(WiiUContentsInformation.java:22)
        at de.mas.wiiu.jnus.implementations.wud.header.WiiUDiscHeader.parseData(WiiUDiscHeader.java:25)
        at de.mas.wiiu.jnus.implementations.wud.WiiUDisc.parseData(WiiUDisc.java:20)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:91)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:69)
        at de.mas.jwudtool.Main.extract(Main.java:209)
        at de.mas.jwudtool.Main.main(Main.java:169)
`

**Comment by Jonah-multi** [comment]
You're missing the correct TitleKey. Find the TitleKey for SBROL (either USA or EUR, make sure you get the right one)

**Comment by leonelhs** [comment]
This an example has worked for me:

`java -jar JWUDTool-0.4.jar -commonkey D7B00402659BA2ABD2CB0DB27FA2B656  -titleKey e8a58307cdb875216e8ca897259b7ad9 -in 'One Piece - Unlimited World Red (Europe) (En,Fr,De,Es,It).wux' -out "extracted" -extract all`
