### ISSUE TITLE
idk what this is

### ISSUE THREAD

**Issue by fishey45** [Maschell/JWUDTool#22]
Extracting WUD
Extracting: C:\Users\cmgui\Downloads
Exception in thread "main" java.io.FileNotFoundException: C:\Users\cmgui\Downloads (Access is denied)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
        at de.mas.wiiu.jnus.implementations.wud.WUDImage.<init>(WUDImage.java:60)
        at de.mas.wiiu.jnus.implementations.wud.WUDImage.<init>(WUDImage.java:51)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:82)
        at de.mas.wiiu.jnus.WUDLoader.load(WUDLoader.java:69)
        at de.mas.jwudtool.Main.extract(Main.java:209)
        at de.mas.jwudtool.Main.main(Main.java:169)

**Comment by darienesf** [comment]
neirad@serebii rom % cd /Users/neirad/Documents/wuxtowud 
neirad@serebii wuxtowud % java -jar JWUDTool.jar -in "Monster Hunter 3 Ultimate (USA).wux" -out "extracted" -extract all
JWUDTool 0.4 - Maschell

Extracting WUD
Extracting: /Users/neirad/Documents/wuxtowud/Monster Hunter 3 Ultimate (USA).wux
Exception in thread "main" java.lang.IllegalArgumentException: Missing argument
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:98)
	at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.init(AESDecryption.java:57)
	at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.init(AESDecryption.java:52)
	at de.mas.wiiu.jnus.utils.cryptography.AESDecryption.<init>(AESDecryption.java:48)
	at de.mas.wiiu.jnus.entities.Ticket.calculateDecryptedKey(Ticket.java:84)
	at de.mas.wiiu.jnus.entities.Ticket.createTicket(Ticket.java:78)
	at de.mas.wiiu.jnus.entities.Ticket.parseTicket(Ticket.java:71)
	at de.mas.wiiu.jnus.NUSTitleLoader.loadNusTitle(NUSTitleLoader.java:68)
	at de.mas.wiiu.jnus.WUDLoader.convertGamePartitionToNUSTitle(WUDLoader.java:113)
	at de.mas.wiiu.jnus.WUDLoader.getGamePartionsAsNUSTitles(WUDLoader.java:103)
	at de.mas.jwudtool.Main.extract(Main.java:219)
	at de.mas.jwudtool.Main.main(Main.java:169)
neirad@serebii wuxtowud % 

I have a simiilar output
